/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2020-03-14 04:00:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class attpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.6.RELEASE.jar", Long.valueOf(1578112505675L));
    _jspx_dependants.put("jar:file:/E:/WS-AceProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/attendance/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
    _jspx_dependants.put("jar:file:/E:/WS-AceProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/attendance/WEB-INF/lib/spring-webmvc-4.3.6.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1485330388000L));
    _jspx_dependants.put("jar:file:/E:/WS-AceProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/attendance/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098691290000L));
    _jspx_dependants.put("/WEB-INF/views/links.jsp", Long.valueOf(1584157304861L));
    _jspx_dependants.put("/WEB-INF/views/navbar.jsp", Long.valueOf(1584133014440L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1570678073570L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fchecked_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fbutton_0026_005fstyle_005fclass;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fchecked_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fbutton_0026_005fstyle_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005faction.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fchecked_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fbutton_0026_005fstyle_005fclass.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" \thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-2.2.1.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js\"></script>  \r\n");
      out.write("  <link href=\"https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".row-flex {\r\n");
      out.write("  display:flex;\r\n");
      out.write("  flex-wrap:wrap;   \r\n");
      out.write("}\r\n");
      out.write(".col-wrap{\r\n");
      out.write("overflow-wrap:break-word;\r\n");
      out.write("justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write(".brdr{\r\n");
      out.write(" \t/*\r\n");
      out.write("   margin-left:1px;\r\n");
      out.write("   margin-right:1px;\r\n");
      out.write("   margin-top:1px;\r\n");
      out.write("   margin-bottom:1px;\r\n");
      out.write("   \r\n");
      out.write("    border:1px solid black;*/    \r\n");
      out.write("   \r\n");
      out.write("    border-radius:15px;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default container navbar-fixed-top\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("     \t<a class=\"navbar-brand\" href=\"#\" style=\"color:black; font-size:30px\">eNcoreVista</a>\r\n");
      out.write("     </div>\r\n");
      out.write("\t    <ul class=\"nav navbar-nav\" >\t      \r\n");
      out.write("\t      <li><a href=\"reqFacPage\" style=\"color:black; font-size:20px; font-weight:bold;\">Faculty</a></li>\r\n");
      out.write("\t      <li><a href=\"reqCHPage\" style=\"color:black; font-size:20px; font-weight:bold;\">Center Head</a></li>\t \r\n");
      out.write("\t    </ul>\r\n");
      out.write("\t     <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t     \t<li><a href=\"#\" style=\"font-family: Times New Roman; font-size:40px; font-weight:bold; color:#0017ad\" >NIIT</a></li>\r\n");
      out.write("\t     </ul>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("<div class=\"container\" style=\"background-color:#c0fae6; margin-top:50px\">\r\n");
      out.write("\t<div class=\"col-sm-12\" style=\"color:black; font-size:30px; font-weight:bold; text-align:center\">\r\n");
      out.write("\t\tAttendance screen\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr style=\"border-top: 1px solid blue\">\r\n");
      out.write("\t<div class=\"row\" style=\"font-style:bold; font-size:15px\">\r\n");
      out.write("\t\t<strong>\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">Batch Code <br> Program</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">Reg. No. <br> Student ID</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3\">Student Name</div>\r\n");
      out.write("\t\t\t<!-- <div class=\"col-sm-2\">Program</div> -->\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">Session No.</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3\">Att. Status</div>\r\n");
      out.write("\t\t</strong>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr style=\"border-top: 1px solid blue\">\r\n");
      out.write("\t");
      if (_jspx_meth_spring_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_spring_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_spring_005fform_005f0_reused = false;
    try {
      _jspx_th_spring_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fform_005f0.setParent(null);
      // /WEB-INF/views/attpage.jsp(27,1) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fform_005f0.setModelAttribute("form");
      // /WEB-INF/views/attpage.jsp(27,1) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fform_005f0.setAction("reqMarkAttendance");
      // /WEB-INF/views/attpage.jsp(27,1) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fform_005f0.setMethod("post");
      int[] _jspx_push_body_count_spring_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fform_005f0 = _jspx_th_spring_005fform_005f0.doStartTag();
        if (_jspx_eval_spring_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t");
            if (_jspx_meth_c_005fforEach_005f0(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t<div class=\"col-sm-12\" style=\"text-align:right; margin-bottom:50px\">\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_spring_005fbutton_005f0(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t</div>\r\n");
            int evalDoAfterBody = _jspx_th_spring_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005faction.reuse(_jspx_th_spring_005fform_005f0);
      _jspx_th_spring_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/attpage.jsp(28,2) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${form.studentrecords}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/attpage.jsp(28,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("st");
      // /WEB-INF/views/attpage.jsp(28,2) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("vs");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\t\t\r\n");
            out.write("\t\t \t");
            if (_jspx_meth_spring_005fhidden_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" \r\n");
            out.write("\t\t \t");
            if (_jspx_meth_spring_005fhidden_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" \t \t\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_spring_005fhidden_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_spring_005fhidden_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\t\t\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_spring_005fhidden_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_spring_005fhidden_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_spring_005fhidden_005f6(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_spring_005fhidden_005f7(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_spring_005fhidden_005f8(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_spring_005fhidden_005f9(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_spring_005fhidden_005f10(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_spring_005fhidden_005f11(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\t\r\n");
            out.write("\t\t\t<div class=\"row\" style=\"font-size:20px\">\t\t\r\n");
            out.write("\t\t\t\t<div class=\"col-sm-2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.batchid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<br>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.crsname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("\t\t\t\t<div class=\"col-sm-2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.regid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<br>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.stid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div> \r\n");
            out.write("\t\t\t\t<div class=\"col-sm-3\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.stname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t<div class=\"col-sm-2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.sessionno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("\t\t\t\t<div class=\"col-sm-3\">\r\n");
            out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_spring_005fradiobutton_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("  Present\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_spring_005fradiobutton_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("  Absent\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t\t");
            out.write("\t\t\r\n");
            out.write("\t\t\t<hr style=\"border-top: 1px solid #008f2d\">\t\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f0 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f0_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(29,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f0.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].batchid", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f0 = _jspx_th_spring_005fhidden_005f0.doStartTag();
        if (_jspx_th_spring_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f0);
      _jspx_th_spring_005fhidden_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f1 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f1_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(30,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f1.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].crsid", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f1 = _jspx_th_spring_005fhidden_005f1.doStartTag();
        if (_jspx_th_spring_005fhidden_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f1);
      _jspx_th_spring_005fhidden_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f2 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f2_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(31,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f2.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].crsname", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f2 = _jspx_th_spring_005fhidden_005f2.doStartTag();
        if (_jspx_th_spring_005fhidden_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f2);
      _jspx_th_spring_005fhidden_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f3 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f3_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(32,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f3.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].nosessions", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f3 = _jspx_th_spring_005fhidden_005f3.doStartTag();
        if (_jspx_th_spring_005fhidden_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f3);
      _jspx_th_spring_005fhidden_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f4 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f4_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(33,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f4.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].status", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f4 = _jspx_th_spring_005fhidden_005f4.doStartTag();
        if (_jspx_th_spring_005fhidden_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f4);
      _jspx_th_spring_005fhidden_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f4, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f5 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f5_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f5.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(34,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f5.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].batchschstid", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f5 = _jspx_th_spring_005fhidden_005f5.doStartTag();
        if (_jspx_th_spring_005fhidden_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f5);
      _jspx_th_spring_005fhidden_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f5, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f6 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f6_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f6.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(35,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f6.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].sessionno", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f6 = _jspx_th_spring_005fhidden_005f6.doStartTag();
        if (_jspx_th_spring_005fhidden_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f6);
      _jspx_th_spring_005fhidden_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f6, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f7 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f7_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f7.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(36,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f7.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].batchschedulestudentsstatus", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f7 = _jspx_th_spring_005fhidden_005f7.doStartTag();
        if (_jspx_th_spring_005fhidden_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f7);
      _jspx_th_spring_005fhidden_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f7, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f8 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f8_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f8.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(37,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f8.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].regid", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f8 = _jspx_th_spring_005fhidden_005f8.doStartTag();
        if (_jspx_th_spring_005fhidden_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f8.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f8);
      _jspx_th_spring_005fhidden_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f8, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f9 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f9_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f9.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(38,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f9.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].studentstatus", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f9 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f9 = _jspx_th_spring_005fhidden_005f9.doStartTag();
        if (_jspx_th_spring_005fhidden_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f9[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f9.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f9.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f9);
      _jspx_th_spring_005fhidden_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f9, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f10 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f10_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f10.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(39,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f10.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].stid", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f10 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f10 = _jspx_th_spring_005fhidden_005f10.doStartTag();
        if (_jspx_th_spring_005fhidden_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f10[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f10.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f10.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f10);
      _jspx_th_spring_005fhidden_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f10, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fhidden_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_spring_005fhidden_005f11 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_spring_005fhidden_005f11_reused = false;
    try {
      _jspx_th_spring_005fhidden_005f11.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fhidden_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(40,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fhidden_005f11.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].stname", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005fhidden_005f11 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fhidden_005f11 = _jspx_th_spring_005fhidden_005f11.doStartTag();
        if (_jspx_th_spring_005fhidden_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fhidden_005f11[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fhidden_005f11.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fhidden_005f11.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005fhidden_005f11);
      _jspx_th_spring_005fhidden_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fhidden_005f11, _jsp_getInstanceManager(), _jspx_th_spring_005fhidden_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fradiobutton_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:radiobutton
    org.springframework.web.servlet.tags.form.RadioButtonTag _jspx_th_spring_005fradiobutton_005f0 = (org.springframework.web.servlet.tags.form.RadioButtonTag) _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fchecked_005fnobody.get(org.springframework.web.servlet.tags.form.RadioButtonTag.class);
    boolean _jspx_th_spring_005fradiobutton_005f0_reused = false;
    try {
      _jspx_th_spring_005fradiobutton_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fradiobutton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(49,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f0.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].attst", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/attpage.jsp(49,6) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f0.setValue("Present");
      // /WEB-INF/views/attpage.jsp(49,6) null
      _jspx_th_spring_005fradiobutton_005f0.setDynamicAttribute(null, "checked", "true");
      int[] _jspx_push_body_count_spring_005fradiobutton_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fradiobutton_005f0 = _jspx_th_spring_005fradiobutton_005f0.doStartTag();
        if (_jspx_th_spring_005fradiobutton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fradiobutton_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fradiobutton_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fradiobutton_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fchecked_005fnobody.reuse(_jspx_th_spring_005fradiobutton_005f0);
      _jspx_th_spring_005fradiobutton_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fradiobutton_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fradiobutton_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fradiobutton_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:radiobutton
    org.springframework.web.servlet.tags.form.RadioButtonTag _jspx_th_spring_005fradiobutton_005f1 = (org.springframework.web.servlet.tags.form.RadioButtonTag) _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.RadioButtonTag.class);
    boolean _jspx_th_spring_005fradiobutton_005f1_reused = false;
    try {
      _jspx_th_spring_005fradiobutton_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fradiobutton_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/attpage.jsp(52,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f1.setPath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("studentrecords[${vs.index}].attst", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/attpage.jsp(52,6) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f1.setValue("Absent");
      int[] _jspx_push_body_count_spring_005fradiobutton_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fradiobutton_005f1 = _jspx_th_spring_005fradiobutton_005f1.doStartTag();
        if (_jspx_th_spring_005fradiobutton_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fradiobutton_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fradiobutton_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fradiobutton_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spring_005fradiobutton_005f1);
      _jspx_th_spring_005fradiobutton_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fradiobutton_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fradiobutton_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fbutton_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:button
    org.springframework.web.servlet.tags.form.ButtonTag _jspx_th_spring_005fbutton_005f0 = (org.springframework.web.servlet.tags.form.ButtonTag) _005fjspx_005ftagPool_005fspring_005fbutton_0026_005fstyle_005fclass.get(org.springframework.web.servlet.tags.form.ButtonTag.class);
    boolean _jspx_th_spring_005fbutton_005f0_reused = false;
    try {
      _jspx_th_spring_005fbutton_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fbutton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/attpage.jsp(60,3) null
      _jspx_th_spring_005fbutton_005f0.setDynamicAttribute(null, "class", "btn btn-success");
      // /WEB-INF/views/attpage.jsp(60,3) null
      _jspx_th_spring_005fbutton_005f0.setDynamicAttribute(null, "style", "font-size:20px; background-color:#8aa3ff; color:green");
      int[] _jspx_push_body_count_spring_005fbutton_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fbutton_005f0 = _jspx_th_spring_005fbutton_005f0.doStartTag();
        if (_jspx_eval_spring_005fbutton_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Mart Attendance");
            int evalDoAfterBody = _jspx_th_spring_005fbutton_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005fbutton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fbutton_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fbutton_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fbutton_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fbutton_0026_005fstyle_005fclass.reuse(_jspx_th_spring_005fbutton_005f0);
      _jspx_th_spring_005fbutton_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbutton_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fbutton_005f0_reused);
    }
    return false;
  }
}
